## Directorio raiz de las radios

export home_radio=/opt/radios

export radios=/etc/radios/radios.conf

## Directorio de los Servidores

export home_server=/opt/radios/servers

## Directorio de Audio Compartido entre Radios

export general_audio=/home/freevo/audio

## Template (Skell Creacion web radios) 

export web_template=/opt/radios/original/web/


## Directorio Raiz Apache.

########### Debian
export directorio_web=/var/www

########### Suse
#export directorio_web=/srv/www

##### Red Hat / CentOS
# export directorio_web=/var/www/html/
