#!/bin/bash
source /opt/radios/config.inc
cd $home_server/$1
find  $general_audio -iname "*.mp3" > playlist.lst
kill -9 `ps aux |grep USR1 |grep -v grep |head -n 1 |awk {'print $2'}`

nohup ./sc_trans_linux$1 sc_trans.conf USR1 2> /dev/null & 
